name: residue
root: <%= ENV['PWD'] %>

windows:
  - worker:
      root: <%= ENV['PWD'] %>/packages/worker
      panes:
        - pnpm dev
  - docs:
      root: <%= ENV['PWD'] %>/docs
      panes:
        - pnpm dev
