name: residue
root: <%= ENV['PWD'] %>

windows:
  - dev:
      layout: even-horizontal
      panes:
        - worker:
            - cd packages/worker
            - pnpm dev
        - docs:
            - cd docs
            - pnpm dev
